export enum Table8 {
  LIBRO_1 = '1',
  LIBRO_2 = '2',
  LIBRO_3 = '3',
  LIBRO_4 = '4',
  LIBRO_5 = '5',
  LIBRO_6 = '6',
  LIBRO_7 = '7',
  LIBRO_8 = '8',
  LIBRO_9 = '9',
  LIBRO_10 = '10',
  LIBRO_11 = '11',
  LIBRO_12 = '12',
  LIBRO_13 = '13',
  LIBRO_14 = '14',
  LIBRO_15 = '15',
  LIBRO_16 = '16',
  LIBRO_17 = '17',
  LIBRO_18 = '18',
  LIBRO_19 = '19',
  LIBRO_20 = '20',
  LIBRO_21 = '21',
  LIBRO_22 = '22',
  LIBRO_23 = '23',
  LIBRO_24 = '24',
  LIBRO_25 = '25',
  LIBRO_26 = '26',
  LIBRO_27 = '27',
  LIBRO_28 = '28',
  LIBRO_29 = '29',
  LIBRO_30 = '30',
  LIBRO_31 = '31',
}

export const TABLE_8_ITEMS: { [key: string]: string } = {
  [Table8.LIBRO_1]: "LIBRO CAJA Y BANCOS",
  [Table8.LIBRO_2]: "LIBRO DE INGRESOS Y GASTOS",
  [Table8.LIBRO_3]: "LIBRO DE INVENTARIOS Y BALANCES",
  [Table8.LIBRO_4]: "LIBRO DE RETENCIONES INCISOS E) Y F) DEL ARTICULO 34° DE LA LEY DEL IMPUESTO A LA RENTA",
  [Table8.LIBRO_5]: "LIBRO DIARIO",
  [Table8.LIBRO_6]: "LIBRO MAYOR",
  [Table8.LIBRO_7]: "REGISTRO DE ACTIVOS FIJOS",
  [Table8.LIBRO_8]: "REGISTRO DE COMPRAS",
  [Table8.LIBRO_9]: "REGISTRO DE CONSIGNACIONES",
  [Table8.LIBRO_10]: "REGISTRO DE COSTOS",
  [Table8.LIBRO_11]: "REGISTRO DE HUÉSPEDES",
  [Table8.LIBRO_12]: "REGISTRO DE INVENTARIO PERMANENTE EN UNIDADES FÍSICAS",
  [Table8.LIBRO_13]: "REGISTRO DE INVENTARIO PERMANENTE VALORIZADO",
  [Table8.LIBRO_14]: "REGISTRO DE VENTAS E INGRESOS",
  [Table8.LIBRO_15]: "REGISTRO DE VENTAS E INGRESOS - ARTÍCULO 23° RESOLUCIÓN DE SUPERINTENDENCIA N° 266-2004/SUNAT",
  [Table8.LIBRO_16]: "REGISTRO DEL RÉGIMEN DE PERCEPCIONES",
  [Table8.LIBRO_17]: "REGISTRO DEL RÉGIMEN DE RETENCIONES",
  [Table8.LIBRO_18]: "REGISTRO IVAP",
  [Table8.LIBRO_19]: "REGISTRO(S) AUXILIAR(ES) DE ADQUISICIONES - ARTÍCULO 8° RESOLUCIÓN DE SUPERINTENDENCIA N° 022-98/SUNAT",
  [Table8.LIBRO_20]: "REGISTRO(S) AUXILIAR(ES) DE ADQUISICIONES - INCISO A) PRIMER PÁRRAFO ARTÍCULO 5° RESOLUCIÓN DE SUPERINTENDENCIA N° 021-99/SUNAT",
  [Table8.LIBRO_21]: "REGISTRO(S) AUXILIAR(ES) DE ADQUISICIONES - INCISO A) PRIMER PÁRRAFO ARTÍCULO 5° RESOLUCIÓN DE SUPERINTENDENCIA N° 142-2001/SUNAT",
  [Table8.LIBRO_22]: "REGISTRO(S) AUXILIAR(ES) DE ADQUISICIONES - INCISO C) PRIMER PÁRRAFO ARTÍCULO 5° RESOLUCIÓN DE SUPERINTENDENCIA N° 256-2004/SUNAT",
  [Table8.LIBRO_23]: "REGISTRO(S) AUXILIAR(ES) DE ADQUISICIONES - INCISO A) PRIMER PÁRRAFO ARTÍCULO 5° RESOLUCIÓN DE SUPERINTENDENCIA N° 257-2004/SUNAT",
  [Table8.LIBRO_24]: "REGISTRO(S) AUXILIAR(ES) DE ADQUISICIONES - INCISO C) PRIMER PÁRRAFO ARTÍCULO 5° RESOLUCIÓN DE SUPERINTENDENCIA N° 258-2004/SUNAT",
  [Table8.LIBRO_25]: "REGISTRO(S) AUXILIAR(ES) DE ADQUISICIONES - INCISO A) PRIMER PÁRRAFO ARTÍCULO 5° RESOLUCIÓN DE SUPERINTENDENCIA N° 259-2004/SUNAT",
  [Table8.LIBRO_26]: "REGISTRO DE RETENCIONES ARTÍCULO 77-A DE LA LEY DEL IMPUESTO A LA RENTA",
  [Table8.LIBRO_27]: "LIBRO DE ACTAS DE LA EMPRESA INDIVIDUAL DE RESPONSABILIDAD LIMITADA",
  [Table8.LIBRO_28]: "LIBRO DE ACTAS DE LA JUNTA GENERAL DE ACCIONISTAS",
  [Table8.LIBRO_29]: "LIBRO DE ACTAS DEL DIRECTORIO",
  [Table8.LIBRO_30]: "LIBRO DE MATRÍCULA DE ACCIONES",
  [Table8.LIBRO_31]: "LIBRO DE PLANILLAS",
};

export function validateCode(libro: string) {
  return Object.values<string>(Table8).includes(libro);
}

export function getName(value: string): string {
  return TABLE_8_ITEMS[value];
}

export function getSQLCase(field: string) {
  var sql = `CASE ${field} `;
  for (let [key, value] of Object.entries(TABLE_8_ITEMS)) {
    sql += `WHEN '${key}' THEN '${value}' `;
  }
  sql += `END`;

  return sql;
}