export const LIBRO_1 = '1';
export const LIBRO_2 = '2';
export const LIBRO_3 = '3';
export const LIBRO_4 = '4';
export const LIBRO_5 = '5';
export const LIBRO_6 = '6';
export const LIBRO_7 = '7';
export const LIBRO_8 = '8';
export const LIBRO_9 = '9';
export const LIBRO_10 = '10';
export const LIBRO_11 = '11';
export const LIBRO_12 = '12';
export const LIBRO_13 = '13';
export const LIBRO_14 = '14';
export const LIBRO_15 = '15';
export const LIBRO_16 = '16';
export const LIBRO_17 = '17';
export const LIBRO_18 = '18';
export const LIBRO_19 = '19';
export const LIBRO_20 = '20';
export const LIBRO_21 = '21';
export const LIBRO_22 = '22';
export const LIBRO_23 = '23';
export const LIBRO_24 = '24';
export const LIBRO_25 = '25';
export const LIBRO_26 = '26';
export const LIBRO_27 = '27';
export const LIBRO_28 = '28';
export const LIBRO_29 = '29';
export const LIBRO_30 = '30';
export const LIBRO_31 = '31';

export const TABLE_8_ITEMS: { [key: string]: string } = {
  [LIBRO_1]: "LIBRO CAJA Y BANCOS",
  [LIBRO_2]: "LIBRO DE INGRESOS Y GASTOS",
  [LIBRO_3]: "LIBRO DE INVENTARIOS Y BALANCES",
  [LIBRO_4]: "LIBRO DE RETENCIONES INCISOS E) Y F) DEL ARTICULO 34° DE LA LEY DEL IMPUESTO A LA RENTA",
  [LIBRO_5]: "LIBRO DIARIO",
  [LIBRO_6]: "LIBRO MAYOR",
  [LIBRO_7]: "REGISTRO DE ACTIVOS FIJOS",
  [LIBRO_8]: "REGISTRO DE COMPRAS",
  [LIBRO_9]: "REGISTRO DE CONSIGNACIONES",
  [LIBRO_10]: "REGISTRO DE COSTOS",
  [LIBRO_11]: "REGISTRO DE HUÉSPEDES",
  [LIBRO_12]: "REGISTRO DE INVENTARIO PERMANENTE EN UNIDADES FÍSICAS",
  [LIBRO_13]: "REGISTRO DE INVENTARIO PERMANENTE VALORIZADO",
  [LIBRO_14]: "REGISTRO DE VENTAS E INGRESOS",
  [LIBRO_15]: "REGISTRO DE VENTAS E INGRESOS - ARTÍCULO 23° RESOLUCIÓN DE SUPERINTENDENCIA N° 266-2004/SUNAT",
  [LIBRO_16]: "REGISTRO DEL RÉGIMEN DE PERCEPCIONES",
  [LIBRO_17]: "REGISTRO DEL RÉGIMEN DE RETENCIONES",
  [LIBRO_18]: "REGISTRO IVAP",
  [LIBRO_19]: "REGISTRO(S) AUXILIAR(ES) DE ADQUISICIONES - ARTÍCULO 8° RESOLUCIÓN DE SUPERINTENDENCIA N° 022-98/SUNAT",
  [LIBRO_20]: "REGISTRO(S) AUXILIAR(ES) DE ADQUISICIONES - INCISO A) PRIMER PÁRRAFO ARTÍCULO 5° RESOLUCIÓN DE SUPERINTENDENCIA N° 021-99/SUNAT",
  [LIBRO_21]: "REGISTRO(S) AUXILIAR(ES) DE ADQUISICIONES - INCISO A) PRIMER PÁRRAFO ARTÍCULO 5° RESOLUCIÓN DE SUPERINTENDENCIA N° 142-2001/SUNAT",
  [LIBRO_22]: "REGISTRO(S) AUXILIAR(ES) DE ADQUISICIONES - INCISO C) PRIMER PÁRRAFO ARTÍCULO 5° RESOLUCIÓN DE SUPERINTENDENCIA N° 256-2004/SUNAT",
  [LIBRO_23]: "REGISTRO(S) AUXILIAR(ES) DE ADQUISICIONES - INCISO A) PRIMER PÁRRAFO ARTÍCULO 5° RESOLUCIÓN DE SUPERINTENDENCIA N° 257-2004/SUNAT",
  [LIBRO_24]: "REGISTRO(S) AUXILIAR(ES) DE ADQUISICIONES - INCISO C) PRIMER PÁRRAFO ARTÍCULO 5° RESOLUCIÓN DE SUPERINTENDENCIA N° 258-2004/SUNAT",
  [LIBRO_25]: "REGISTRO(S) AUXILIAR(ES) DE ADQUISICIONES - INCISO A) PRIMER PÁRRAFO ARTÍCULO 5° RESOLUCIÓN DE SUPERINTENDENCIA N° 259-2004/SUNAT",
  [LIBRO_26]: "REGISTRO DE RETENCIONES ARTÍCULO 77-A DE LA LEY DEL IMPUESTO A LA RENTA",
  [LIBRO_27]: "LIBRO DE ACTAS DE LA EMPRESA INDIVIDUAL DE RESPONSABILIDAD LIMITADA",
  [LIBRO_28]: "LIBRO DE ACTAS DE LA JUNTA GENERAL DE ACCIONISTAS",
  [LIBRO_29]: "LIBRO DE ACTAS DEL DIRECTORIO",
  [LIBRO_30]: "LIBRO DE MATRÍCULA DE ACCIONES",
  [LIBRO_31]: "LIBRO DE PLANILLAS",
};

export function getName(value: string): string {
  return TABLE_8_ITEMS[value];
}

export function getSQLCase(field: string) {
  var sql = `CASE ${field} `;
  for (let [key, value] of Object.entries(TABLE_8_ITEMS)) {
    sql += `WHEN '${key}' THEN '${value}' `;
  }
  sql += `END`;

  return sql;
}